package com.itb.tcc.mif3an.pizzaria.model.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Permission {
    // Funcionario
    FUNCIONARIO_READ("FUNCIONARIO_READ"),
    FUNCIONARIO_UPDATE("FUNCIONARIO_UPDATE"),
    FUNCIONARIO_DELETE("FUNCIONARIO_DELETE"),
    FUNCIONARIO_CREATE("FUNCIONARIO_CREATE"),
    FUNCIONARIO_LIST("FUNCIONARIO_LIST"),
    FUNCIONARIO_MANAGER("FUNCIONARIO_MANAGE"),


    // Cliente
    CLIENTE_READ("CLIENTE_READ"),
    CLIENTE_UPDATE("CLIENTE_UPDATE"),
    CLIENTE_DELETE("CLIENTE_DELETE"),
    CLIENTE_CREATE("CLIENTE_CREATE"),
    CLIENTE_LIST("CLIENTE_LIST"),
    CLIENTE_MANAGER("CLIENTE_MANAGE"),


    // Pedido
    PEDIDO_READ("PEDIDO_READ"),
    PEDIDO_UPDATE("PEDIDO_UPDATE"),
    PEDIDO_DELETE("PEDIDO_DELETE"),
    PEDIDO_CREATE("PEDIDO_CREATE"),
    PEDIDO_MANAGE("PEDIDO_MANAGE"),
    PEDIDO_LIST("PEDIDO_LIST"),


    // Categoria
    CATEGORIA_READ("CATEGORIA_READ"),
    CATEGORIA_UPDATE("CATEGORIA_UPDATE"),
    CATEGORIA_DELETE("CATEGORIA_DELETE"),
    CATEGORIA_CREATE("CATEGORIA_CREATE"),
    CATEGORIA_MANAGE("CATEGORIA_MANAGE"),


    // Produto
    PRODUTO_READ("PRODUTO_READ"),
    PRODUTO_UPDATE("PRODUTO_UPDATE"),
    PRODUTO_DELETE("PRODUTO_DELETE"),
    PRODUTO_CREATE("PRODUTO_CREATE"),
    PRODUTO_MANAGE("PRODUTO_MANAGE");


    private final String permission;

}
